branches:
  only:
    - master
    - dev

language: node_js

node_js: 6.0


before_script:
  - npm install

script:
  - npm run test
  - npm run coveralls
  - npm run coverage

notifications:
  email: false
