branches:
  only:
    - master
    - dev

language: node_js

node_js: 6.0

env:
  BACKBONE:
    - "1.2"
    - "1.3"
  JQUERY:
    - "1"
    - "2"
    - "3"

matrix:
  include:
    # underscore tests
    - env: UNDERSCORE=1.5
    - env: UNDERSCORE=1.6
    - env: UNDERSCORE=1.7
    - env: UNDERSCORE=1.8
    # lodash tests
    - env: LODASH=3
    - env: LODASH=4

cache:
  directories:
    - node_modules

install:
  - ./ci.sh

script:
  - npm run test
  - npm run coverage

notifications:
  email: false
