branches:
  only:
    - master
    - dev

language: node_js

node_js:
- 6.0.0
- 4.4.0
- 4.0.0
- 0.12.0


before_script:
  - npm install

script:
  - npm run test
  - npm run coveralls

notifications:
  email: false