branches:
  only:
    - master
    - dev

language: node_js

node_js: 6.0

matrix:
  include:
    - env: BACKBONE=1.3 UNDERSCORE=1.8 JQUERY=2
    - env: BACKBONE=1.3 UNDERSCORE=1.8 JQUERY=3
    - env: BACKBONE=1.3 UNDERSCORE=1.8 ZEPTO=1.2

    - env: BACKBONE=1.3 LODASH=3 JQUERY=2
    - env: BACKBONE=1.3 LODASH=3 JQUERY=3
    - env: BACKBONE=1.3 LODASH=3 ZEPTO=1.2

    - env: BACKBONE=1.3 LODASH=4 JQUERY=2
    - env: BACKBONE=1.3 LODASH=4 JQUERY=3
    - env: BACKBONE=1.3 LODASH=4 ZEPTO=1.2

cache:
  directories:
    - node_modules

before_script:
  - ./ci.sh

script:
  - npm run test
  - npm run coverage

notifications:
  email: false
