branches:
  only:
    - master
    - dev

language: node_js

node_js: 6.0

matrix:
  include:
    # backbone@1.2
    - env: BACKBONE=1.2.3 UNDERSCORE=1.7.0
    - env: BACKBONE=1.2.3 UNDERSCORE=1.8.3
    - env: BACKBONE=1.2.3 LODASH=3
    - env: BACKBONE=1.2.3 LODASH=4
    # backbone@1.3
    - env: BACKBONE=1.3.3 UNDERSCORE=1.7.0
    - env: BACKBONE=1.3.3 UNDERSCORE=1.8.3
    - env: BACKBONE=1.3.3 LODASH=3
    - env: BACKBONE=1.3.3 LODASH=4
    # jquery support
    - env: JQUERY=1
    - env: JQUERY=2
    - env: JQUERY=3

cache:
  directories:
    - node_modules

install:
  - ./ci.sh

script:
  - npm run test
  - npm run coverage

notifications:
  email: false
