branches:
  only:
    - master
    - dev

language: node_js

node_js:
- 6.0.x
- 4.4.x
- 4.0.x
- 0.12.x


before_script:
  - npm install

script:
  - npm run test
  - npm run coveralls

notifications:
  email: false